### ISSUE TITLE
如何获取数据点类型

### ISSUE THREAD

**Issue by bert1020** [calimero-project/calimero-server#27]
![image](https://github.com/user-attachments/assets/2469a97b-396a-41e6-bc71-f659651a4884)
当我在onSubnetFrameReceived接收到数据的时候,我怎么解析他的数据类型

**Comment by bmalinowsky** [comment]
Yes, when you need the exact type, you have to know the DPT configuration, e.g., from the ETS.

An example how to decode data using matching DPTs without knowing the exact type is here in the command-line tools:
[decodeAsduByLength(final byte[] asdu, final boolean optimized)](https://github.com/calimero-project/calimero-tools/blob/a806d8c9523e1271528ae64f6802ab300149da45/src/io/calimero/tools/ProcComm.java#L784)
