### ISSUE TITLE
onServerFrameReceived是不是就是通过3671端口收到的?

### ISSUE THREAD

**Issue by bert1020** [calimero-project/calimero-server#28]
现在我用您的程序通过源码运行了一个 knx server ,ETS5可以连接到我这个服务了,在ETS上往这个发送消息,knx server的 KnxServerGateway 类onServerFrameReceived这里可以收到了.

我想在往网络上发 ,让ETS可以收到我发的,我该怎么发送?

现在没有总线,只是我电脑运行knx server ,另外一台电脑打开ETS连接我这个knx server.
我想这应该是叫做网络组播吧

**Comment by bmalinowsky** [comment]
Which message do you want the ETS to receive? The ETS does receive the message it sent as a confirmation. Also, the ETS will show the sent message, e.g., a group value read, in its group monitor. Multicast is done in KNX via KNXnet/IP routing.
